// Frontend Role-Permission mapping mirroring the backend rules

export const PERMISSIONS = {
  DASHBOARD_VIEW: "dashboard.view",
  BOOKINGS_VIEW: "bookings.view",
  BOOKINGS_VERIFY: "bookings.verify",
  ACCOUNTING_VIEW: "accounting.view",
  USERS_VIEW: "users.view",
  TASKS_VIEW: "tasks.view",
  TASKS_VIEW_ALL: "tasks.view_all",
  VENDORS_VIEW: "vendors.view",
  TRIPS_VIEW: "trips.view",
  OPS_VIEW: "ops.view",
  ANNOUNCEMENTS_VIEW: "announcements.view",
  SETTINGS_VIEW: "settings.view",
  REPORTS_VIEW: "reports.view",
} as const;

export const ROLE_PERMISSIONS: Record<string, string[]> = {
  superadmin: [
    "dashboard.view",
    "trips.view",
    "trips.create",
    "trips.edit",
    "trips.publish",
    "trips.archive",
    "trips.delete",
    "bookings.view",
    "bookings.create",
    "bookings.edit",
    "bookings.approve",
    "bookings.reject",
    "payments.view",
    "payments.edit",
    "inquiries.view",
    "inquiries.create",
    "inquiries.edit",
    "quotations.view",
    "quotations.create",
    "quotations.edit",
    "customers.view",
    "customers.export",
    "pagebuilder.view",
    "pagebuilder.edit",
    "seo.view",
    "seo.edit",
    "guides.view",
    "guides.manage",
    "operations.view",
    "operations.edit",
    "reports.view",
    "reports.export",
    "users.view",
    "users.manage",
    "roles.manage",
    "audit.view",
    "settings.view",
    "settings.edit",
    "tickets.view",
    "tickets.create",
    "tickets.edit",
    "tickets.submit",
    "tickets.approve",
    "tickets.reopen",
    "tickets.bulk",
    "tickets.templates.manage",
    "tickets.alerts.view",
    "accounting.view",
    "accounting.edit",
    "emails.manage_templates",
    "tasks.view_all",
    "station_payments.view",
    "station_payments.collect",
    "station_payments.edit_before_handover",
    "station_payments.cancel",
    "station_payments.handover",
    "station_payments.receive",
    "station_payments.reconcile",
    "station_payments.export",
    "station_payments.resend_receipt",
    "station_payments.manage_accounts",
    "station_payments.verify_upi",
    "announcements.view",
  ],

  admin: [
    "dashboard.view",
    "trips.view",
    "trips.create",
    "trips.edit",
    "trips.publish",
    "trips.archive",
    "bookings.view",
    "bookings.create",
    "bookings.edit",
    "bookings.approve",
    "bookings.reject",
    "payments.view",
    "payments.edit",
    "inquiries.view",
    "inquiries.create",
    "inquiries.edit",
    "quotations.view",
    "quotations.create",
    "quotations.edit",
    "customers.view",
    "guides.view",
    "guides.manage",
    "operations.view",
    "operations.edit",
    "reports.view",
    "reports.export",
    "settings.view",
    "hr.view",
    "tickets.view",
    "tickets.create",
    "tickets.edit",
    "tickets.submit",
    "tickets.approve",
    "tickets.reopen",
    "tickets.bulk",
    "tickets.templates.manage",
    "tickets.alerts.view",
    "emails.manage_templates",
    "station_payments.view",
    "station_payments.collect",
    "station_payments.handover",
    "station_payments.receive",
    "station_payments.reconcile",
    "station_payments.resend_receipt",
    "announcements.view",
    "tasks.view_all",
  ],

  sales: [
    "dashboard.view",
    "bookings.view",
    "bookings.create",
    "bookings.edit",
    "payments.view",
    "accounting.submit",
    "inquiries.view",
    "inquiries.create",
    "inquiries.edit",
    "quotations.view",
    "quotations.create",
    "quotations.edit",
    "hr.view",
    "tickets.view",
    "tickets.create",
    "tickets.edit",
    "tickets.submit",
    "tickets.bulk",
    "tickets.alerts.view",
    "announcements.view",
  ],

  operations: [
    "dashboard.view",
    "trips.view",
    "bookings.view",
    "bookings.edit",
    "operations.view",
    "operations.edit",
    "guides.view",
    "hr.view",
    "tickets.view",
    "tickets.create",
    "tickets.edit",
    "tickets.submit",
    "tickets.approve",
    "tickets.reopen",
    "tickets.bulk",
    "tickets.templates.manage",
    "tickets.alerts.view",
    "station_payments.view",
    "station_payments.collect",
    "station_payments.handover",
    "announcements.view",
  ],

  finance: [
    "dashboard.view",
    "bookings.view",
    "bookings.edit",
    "payments.view",
    "payments.edit",
    "reports.view",
    "hr.view",
    "accounting.view",
    "accounting.edit",
    "station_payments.view",
    "station_payments.collect",
    "station_payments.receive",
    "station_payments.reconcile",
    "station_payments.manage_accounts",
    "announcements.view",
  ],

  finance_controller: [
    "dashboard.view",
    "bookings.view",
    "payments.view",
    "reports.view",
    "accounting.view",
    "accounting.edit",
    "accounting.approve",
    "finance.control_center.view",
    "finance.incoming.verify",
    "finance.incoming.approve",
    "finance.cash.verify",
    "finance.cash.approve",
    "finance.cash.reject",
    "finance.outgoing.verify",
    "finance.outgoing.approve",
    "finance.outgoing.pay",
    "finance.tickets.verify",
    "finance.tickets.approve",
    "finance.refund.create",
    "finance.refund.view",
    "finance.refund.approve",
    "finance.refund.reject",
    "finance.credit.view",
    "finance.credit.apply",
    "finance.coupons.view",
    "finance.coupons.manage",
    "finance.ticketing.view",
    "finance.ticketing.create",
    "finance.ticketing.verify",
    "finance.ticketing.approve",
    "finance.ticketing.bulk",
    "finance.services.view",
    "finance.services.manage",
    "finance.services.verify",
    "finance.tasks.view",
    "finance.tasks.manage",
    "finance.tasks.comment",
    "finance.audit.view",
    "finance.audit.export",
    "finance.accounting.view",
    "finance.accounting.manage",
    "finance.discrepancy.manage",
    "finance.reports.export",
    "station_payments.view",
    "station_payments.receive",
    "station_payments.reconcile",
    "station_payments.manage_accounts",
    "vendors.view",
    "tickets.view",
    "audit_logs.view",
    "customers.timeline.view",
    "announcements.view",
    "tasks.view_all",
  ],

  FINANCE_CONTROLLER: [
    "dashboard.view",
    "bookings.view",
    "payments.view",
    "reports.view",
    "accounting.view",
    "accounting.edit",
    "accounting.approve",
    "finance.control_center.view",
    "finance.incoming.verify",
    "finance.incoming.approve",
    "finance.cash.verify",
    "finance.cash.approve",
    "finance.cash.reject",
    "finance.outgoing.verify",
    "finance.outgoing.approve",
    "finance.outgoing.pay",
    "finance.tickets.verify",
    "finance.tickets.approve",
    "finance.refund.create",
    "finance.refund.view",
    "finance.refund.approve",
    "finance.refund.reject",
    "finance.credit.view",
    "finance.credit.apply",
    "finance.coupons.view",
    "finance.coupons.manage",
    "finance.ticketing.view",
    "finance.ticketing.create",
    "finance.ticketing.verify",
    "finance.ticketing.approve",
    "finance.ticketing.bulk",
    "finance.services.view",
    "finance.services.manage",
    "finance.services.verify",
    "finance.tasks.view",
    "finance.tasks.manage",
    "finance.tasks.comment",
    "finance.audit.view",
    "finance.audit.export",
    "finance.accounting.view",
    "finance.accounting.manage",
    "finance.discrepancy.manage",
    "finance.reports.export",
    "station_payments.view",
    "station_payments.receive",
    "station_payments.reconcile",
    "station_payments.manage_accounts",
    "vendors.view",
    "tickets.view",
    "audit_logs.view",
    "customers.timeline.view",
    "announcements.view",
    "tasks.view_all",
  ],

  guide: [
    "dashboard.view",
    "trips.view",
    "bookings.view",
    "operations.view",
    "operations.edit",
    "hr.view",
    "tickets.view",
    "tickets.create",
    "tickets.edit",
    "tickets.submit",
    "tickets.approve",
    "announcements.view",
  ],

  viewer: [
    "dashboard.view",
    "trips.view",
    "bookings.view",
    "inquiries.view",
    "quotations.view",
    "reports.view",
    "announcements.view",
  ],

  booking_verifier: [
    "dashboard.view",
    "bookings.view",
    "bookings.verify",
    "tickets.view",
    "tickets.create",
    "tickets.edit",
    "tickets.submit",
    "tickets.approve",
    "tickets.reopen",
    "tickets.bulk",
    "tickets.templates.manage",
    "tickets.alerts.view",
    "announcements.view",
  ],
};

const ROLE_PERMISSIONS_SETS: Record<string, Set<string>> = Object.fromEntries(
  Object.entries(ROLE_PERMISSIONS).map(([k, v]) => [k, new Set(v)]),
);

export function hasPermission(
  permissionsOrRole: readonly string[] | string | null | undefined,
  required: string,
  role?: string,
): boolean {
  if (typeof permissionsOrRole === "string") {
    const normalizedRole = permissionsOrRole.toLowerCase();
    if (normalizedRole === "superadmin" || normalizedRole === "founder") return true;
    const set = ROLE_PERMISSIONS_SETS[normalizedRole];
    if (!set) return false;
    return set.has(required);
  }

  const normRole = role?.toLowerCase();
  if (normRole === "superadmin" || normRole === "founder") return true;

  // Build combined permissions set from role defaults + custom permissions
  const roleDefaults = normRole ? (ROLE_PERMISSIONS[normRole] || []) : [];
  const customPerms = Array.isArray(permissionsOrRole) ? permissionsOrRole : [];
  const combined = new Set([...roleDefaults, ...customPerms]);

  if (combined.has(required)) return true;

  // Check common permission aliases
  if (required === "ops.view" || required === "operations.view") {
    return combined.has("ops.view") || combined.has("operations.view") || combined.has("trips.view");
  }
  if (required.startsWith("vendors.")) {
    return combined.has("vendors.view") || combined.has("vendors.manage") || combined.has("operations.view") || combined.has("ops.view");
  }
  if (required.startsWith("trips.")) {
    return combined.has("trips.view") || combined.has("trips.create") || combined.has("trips.edit") || combined.has("operations.view");
  }

  return false;
}

export function hasAnyPermission(
  permissions: readonly string[] | null | undefined,
  requiredPermissions: string[],
  role?: string,
): boolean {
  const normRole = role?.toLowerCase();
  if (normRole === "superadmin" || normRole === "founder") return true;
  if (!permissions) return false;
  return requiredPermissions.some((p) => permissions.includes(p));
}

export function hasAllPermissions(
  permissions: readonly string[] | null | undefined,
  requiredPermissions: string[],
  role?: string,
): boolean {
  const normRole = role?.toLowerCase();
  if (normRole === "superadmin" || normRole === "founder") return true;
  if (!permissions) return false;
  return requiredPermissions.every((p) => permissions.includes(p));
}
